2023-01-25 00:13:21,226 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 00:13:21,251 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 00:13:21,252 apscheduler.scheduler INFO     Scheduler started
2023-01-25 00:13:38,284 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 00:13:38,317 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 00:13:38,319 apscheduler.scheduler INFO     Scheduler started
2023-01-25 00:13:38,775 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-25 11:10:41,974 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 11:10:42,028 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 11:10:42,029 apscheduler.scheduler INFO     Scheduler started
2023-01-25 11:10:57,786 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 11:10:57,814 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 11:10:57,817 apscheduler.scheduler INFO     Scheduler started
2023-01-25 11:10:58,211 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-25 11:13:10,480 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 11:13:10,509 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 11:13:10,510 apscheduler.scheduler INFO     Scheduler started
2023-01-25 11:13:23,970 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 11:13:23,996 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 11:13:23,997 apscheduler.scheduler INFO     Scheduler started
2023-01-25 11:13:24,481 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-25 13:00:19,963 django.request ERROR    Internal Server Error: /api/selectedcandidate/getfamilydetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 553, in get_raw_data_form
    serializer = view.get_serializer()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'familydetailsview' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
2023-01-25 13:00:20,681 django.request WARNING  Not Found: /favicon.ico
2023-01-25 13:24:19,404 django.request ERROR    Internal Server Error: /api/selectedcandidate/updatefamilydetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 14:16:29,667 django.request WARNING  Bad Request: /api/selectedcandidate/updatefamilydetails
2023-01-25 14:20:52,412 django.request WARNING  Bad Request: /api/selectedcandidate/createfamilydetail
2023-01-25 14:28:28,827 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\selectedcandidate\views\familydetailsview.py changed, reloading.
2023-01-25 14:29:16,170 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 14:29:16,226 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 14:29:16,227 apscheduler.scheduler INFO     Scheduler started
2023-01-25 14:29:16,955 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-25 14:44:58,642 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 14:45:20,494 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 14:53:39,915 django.request ERROR    Internal Server Error: /api/selectedcandidate/updatefamilydetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 15:01:53,774 django.request ERROR    Internal Server Error: /api/selectedcandidate/updatefamilydetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 15:03:28,110 django.request ERROR    Internal Server Error: /api/selectedcandidate/updatefamilydetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 15:04:17,832 django.request ERROR    Internal Server Error: /api/selectedcandidate/updatefamilydetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 16:39:41,689 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 16:39:41,707 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 16:39:41,708 apscheduler.scheduler INFO     Scheduler started
2023-01-25 16:40:28,133 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 16:40:28,162 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 16:40:28,163 apscheduler.scheduler INFO     Scheduler started
2023-01-25 16:40:44,532 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 16:40:44,565 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 16:40:44,572 apscheduler.scheduler INFO     Scheduler started
2023-01-25 16:40:45,024 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-25 17:11:19,299 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 17:11:23,946 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-25 17:11:52,128 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 17:11:52,156 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 17:11:52,157 apscheduler.scheduler INFO     Scheduler started
2023-01-25 17:11:52,700 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-25 17:24:05,400 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-25 17:34:10,385 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-25 18:57:20,838 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 18:57:20,860 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 18:57:20,867 apscheduler.scheduler INFO     Scheduler started
2023-01-25 18:57:55,176 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 18:57:55,180 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 18:57:55,180 apscheduler.scheduler INFO     Scheduler started
2023-01-25 18:57:55,300 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-25 19:01:51,992 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 19:01:52,014 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 19:01:52,015 apscheduler.scheduler INFO     Scheduler started
2023-01-25 19:02:02,540 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 19:02:02,562 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 19:02:02,564 apscheduler.scheduler INFO     Scheduler started
2023-01-25 19:02:02,887 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-25 19:02:45,184 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 19:02:45,235 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 19:02:45,237 apscheduler.scheduler INFO     Scheduler started
2023-01-25 19:02:55,449 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-25 19:02:55,463 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-25 19:02:55,464 apscheduler.scheduler INFO     Scheduler started
2023-01-25 19:02:55,773 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 10:16:05,204 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 10:16:05,227 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 10:16:05,228 apscheduler.scheduler INFO     Scheduler started
2023-01-27 10:16:28,873 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 10:16:28,891 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 10:16:28,892 apscheduler.scheduler INFO     Scheduler started
2023-01-27 10:16:29,222 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 10:22:10,506 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-27 10:22:33,773 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 10:22:33,795 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 10:22:33,796 apscheduler.scheduler INFO     Scheduler started
2023-01-27 10:22:34,087 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 10:47:18,764 django.request WARNING  Not Found: /api/candidate/previewannexure
2023-01-27 10:48:44,296 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\urls.py changed, reloading.
2023-01-27 10:48:57,337 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 10:48:57,355 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 10:48:57,355 apscheduler.scheduler INFO     Scheduler started
2023-01-27 10:48:57,575 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 10:51:10,188 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\urls.py changed, reloading.
2023-01-27 10:51:21,900 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 10:51:21,963 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 10:51:21,965 apscheduler.scheduler INFO     Scheduler started
2023-01-27 10:51:22,513 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 10:51:54,910 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\urls.py changed, reloading.
2023-01-27 10:52:03,605 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 10:52:03,616 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 10:52:03,617 apscheduler.scheduler INFO     Scheduler started
2023-01-27 10:52:03,804 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 10:52:42,619 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\urls.py changed, reloading.
2023-01-27 10:52:51,652 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 10:52:51,665 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 10:52:51,666 apscheduler.scheduler INFO     Scheduler started
2023-01-27 10:52:51,878 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 11:10:39,253 django.request WARNING  Not Found: /api/candidate/previewannexureactionsagaworker
2023-01-27 11:15:43,116 django.request WARNING  Not Found: /api/candidate/previewannexureactionsagaworker
2023-01-27 14:06:51,670 django.request WARNING  Bad Request: /api/selectedcandidate/deletedocument
2023-01-27 14:25:32,688 django.request ERROR    Internal Server Error: /api/selectedcandidate/deletefamilydetail
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-27 14:25:39,699 django.request ERROR    Internal Server Error: /api/selectedcandidate/deletefamilydetail
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-27 14:26:44,752 django.request ERROR    Internal Server Error: /api/selectedcandidate/deletefamilydetail
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-27 14:31:01,547 django.request ERROR    Internal Server Error: /api/selectedcandidate/deletefamilydetail
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-27 14:41:58,523 django.request ERROR    Internal Server Error: /api/selectedcandidate/createeducationdetail
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-27 15:32:50,014 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-27 15:33:03,737 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 15:33:03,755 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 15:33:03,756 apscheduler.scheduler INFO     Scheduler started
2023-01-27 15:33:04,006 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 15:54:51,579 django.request WARNING  Not Found: /api/candidate/getannexuredetails
2023-01-27 15:56:12,042 django.request WARNING  Not Found: /api/candidate/getannexuredetails
2023-01-27 15:57:50,871 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 97, in getAnnexureDetails
    Isvariable = request.data["isvariable"]
KeyError: 'isvariable'
2023-01-27 16:16:27,308 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-27 16:16:47,240 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 16:16:47,266 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 16:16:47,267 apscheduler.scheduler INFO     Scheduler started
2023-01-27 16:16:47,563 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 16:17:00,881 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 97, in getAnnexureDetails
    Isvariable = request.data["Isvariable"]
KeyError: 'Isvariable'
2023-01-27 16:18:35,997 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 97, in getAnnexureDetails
    Isvariable = request.data["Isvariable"]
KeyError: 'Isvariable'
2023-01-27 16:18:56,297 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 97, in getAnnexureDetails
    Isvariable = request.data["Isvariable"]
KeyError: 'Isvariable'
2023-01-27 16:21:32,472 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-27 16:21:43,285 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 16:21:43,302 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 16:21:43,302 apscheduler.scheduler INFO     Scheduler started
2023-01-27 16:21:43,563 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 16:22:07,886 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 100, in getAnnexureDetails
    Is_Eligible_annu_Mgnt_Bonus=request.data["IS_Eligible_annu_Mgnt_Bonus"]
KeyError: 'IS_Eligible_annu_Mgnt_Bonus'
2023-01-27 16:22:43,720 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-27 16:23:03,977 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 16:23:04,000 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 16:23:04,003 apscheduler.scheduler INFO     Scheduler started
2023-01-27 16:23:04,319 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 16:23:27,463 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 105, in getAnnexureDetails
    FixedCTC, Isvariable, VariablePay, MQVariable, Is_Eligible_annu_Mgnt_Bonus,
NameError: name 'Isvariable' is not defined
2023-01-27 16:23:51,902 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-27 16:24:01,648 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 16:24:01,661 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 16:24:01,662 apscheduler.scheduler INFO     Scheduler started
2023-01-27 16:24:01,894 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 16:37:01,218 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 92, in getAnnexureDetails
    designation= Designation.objects.get(DesignationId=request.data['designation'])
KeyError: 'designation'
2023-01-27 16:37:35,432 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:37:52,810 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:38:10,540 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:38:23,160 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:41:17,342 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:54:50,041 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:56:46,850 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:57:05,186 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:57:26,169 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 16:57:48,127 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 17:00:35,251 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 17:01:18,997 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 17:02:06,529 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 17:02:07,661 django.request ERROR    Internal Server Error: /api/candidate/updateselectedcandidate
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PermissionError is not JSON serializable
2023-01-27 17:04:50,750 django.utils.autoreload INFO     C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py changed, reloading.
2023-01-27 17:05:09,312 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-27 17:05:09,333 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-27 17:05:09,336 apscheduler.scheduler INFO     Scheduler started
2023-01-27 17:05:09,769 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-27 17:27:16,543 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:27:35,585 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:30:27,908 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:31:30,118 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:32:53,598 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:33:15,184 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:36:13,510 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:40:11,755 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:42:07,263 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
KeyError: 'selectedcandidateid'
2023-01-27 17:54:00,044 apscheduler.executors.default INFO     Running job "simulatejob (trigger: cron[day_of_week='mon-sun', hour='17', minute='54'], next run at: 2023-01-28 17:54:00 IST)" (scheduled at 2023-01-27 17:54:00+05:30)
2023-01-27 17:54:00,046 apscheduler.executors.default INFO     Job "simulatejob (trigger: cron[day_of_week='mon-sun', hour='17', minute='54'], next run at: 2023-01-28 17:54:00 IST)" executed successfully
2023-01-27 17:54:00,790 apscheduler.executors.default INFO     Running job "simulatejob (trigger: cron[day_of_week='mon-sun', hour='17', minute='54'], next run at: 2023-01-28 17:54:00 IST)" (scheduled at 2023-01-27 17:54:00+05:30)
2023-01-27 17:54:00,799 apscheduler.executors.default INFO     Job "simulatejob (trigger: cron[day_of_week='mon-sun', hour='17', minute='54'], next run at: 2023-01-28 17:54:00 IST)" executed successfully
2023-01-27 19:26:15,982 django.request WARNING  Not Found: /api/candidate/previewannexure
2023-01-27 19:26:36,520 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 92, in getAnnexureDetails
    designation= Designation.objects.get(DesignationId=request.data['designation'])
KeyError: 'designation'
2023-01-27 19:27:54,771 django.request WARNING  Bad Request: /api/candidate/getAnnexureDetails
2023-01-27 19:28:17,744 django.request WARNING  Bad Request: /api/candidate/getAnnexureDetails
2023-01-27 19:28:33,449 django.request WARNING  Bad Request: /api/candidate/getAnnexureDetails
2023-01-27 19:28:39,468 django.request WARNING  Bad Request: /api/candidate/getAnnexureDetails
2023-01-27 19:29:47,945 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'selectedcandidateid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'selectedcandidateid'
2023-01-27 19:29:48,591 django.request WARNING  Bad Request: /api/candidate/getAnnexureDetails
2023-01-27 19:30:21,324 django.request WARNING  Bad Request: /api/candidate/getAnnexureDetails
2023-01-27 19:32:18,120 django.request ERROR    Internal Server Error: /api/candidate/getAnnexureDetails
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'selectedcandidateid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\work\serveron12dec\Hrportalserver\candidate\views\updateselectedcandidate.py", line 91, in getAnnexureDetails
    selectedcandidate =  Selected_Candidates.objects.get(Selected_Candidate_ID=request.data["selectedcandidateid"])
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'selectedcandidateid'
2023-01-28 11:58:52,281 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-28 11:58:52,299 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-28 11:58:52,299 apscheduler.scheduler INFO     Scheduler started
2023-01-28 11:59:01,492 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-28 11:59:01,506 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-28 11:59:01,506 apscheduler.scheduler INFO     Scheduler started
2023-01-28 11:59:01,723 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-28 19:54:55,197 apscheduler.executors.default WARNING  Run time of job "simulatejob (trigger: cron[day_of_week='mon-sun', hour='17', minute='54'], next run at: 2023-01-29 17:54:00 IST)" was missed by 2:00:55.196106
2023-01-28 19:54:55,239 apscheduler.executors.default WARNING  Run time of job "simulatejob (trigger: cron[day_of_week='mon-sun', hour='17', minute='54'], next run at: 2023-01-29 17:54:00 IST)" was missed by 2:00:55.238108
2023-01-30 11:00:38,442 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-30 11:00:38,470 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-30 11:00:38,471 apscheduler.scheduler INFO     Scheduler started
2023-01-30 11:00:51,218 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-01-30 11:00:51,239 apscheduler.scheduler INFO     Added job "simulatejob" to job store "default"
2023-01-30 11:00:51,240 apscheduler.scheduler INFO     Scheduler started
2023-01-30 11:00:51,631 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-01-30 12:51:22,944 django.request ERROR    Internal Server Error: /api/selectedcandidate/createemployementdetail
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-30 13:07:29,767 django.request ERROR    Internal Server Error: /api/selectedcandidate/createemployementdetail
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2023-01-30 14:26:07,993 django.request ERROR    Internal Server Error: /api/selectedcandidate/createemployementdetail
Traceback (most recent call last):
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\work\serveron12dec\Hrportalserver\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
